name: "Build CMake project using Ccache"
description: "Build a CMake project. Save Ccache cache after a successful build."
inputs:
  vm:
    description: "The virtual machine used for the build."
    required: true
  build-dir:
    description: "The project's build directory."
    required: false
    default: "${{ github.workspace }}/build"

runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ github.job }}-ccache-${{ github.run_id }}
        restore-keys: ${{ github.job }}-ccache-

    - shell: bash -e {0}
      run: |
        if test -d ${{ env.CCACHE_DIR }}; then
          rsync --archive --stats ${{ env.CCACHE_DIR }}/ ${{ inputs.vm }}:${{ env.CCACHE_DIR }}
          rm -rf ${{ env.CCACHE_DIR }}
        fi

    - shell: ${{ inputs.vm }} {0}
      run: ccache --zero-stats

    - shell: ${{ inputs.vm }} {0}
      run: cmake --build ${{ inputs.build-dir }} -- -j ${{ env.CI_NCPU }}

    - shell: ${{ inputs.vm }} {0}
      run: |
        ccache --version | head -1
        ccache --cleanup
        ccache --show-stats --verbose >/dev/null 2>&1 && ccache --show-stats --verbose || ccache --show-stats
        ccache --show-compression >/dev/null 2>&1 && ccache --show-compression || true
        du -sh ${{ env.CCACHE_DIR }}

    - shell: bash -e {0}
      run: rsync --archive --stats ${{ inputs.vm }}:${{ env.CCACHE_DIR }}/ ${{ env.CCACHE_DIR }}

    - shell: ${{ inputs.vm }} {0}
      run: rm -rf ${{ env.CCACHE_DIR }}

    - uses: actions/cache/save@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ github.job }}-ccache-${{ github.run_id }}

    - shell: bash -e {0}
      run: rm -rf ${{ env.CCACHE_DIR }}
