name: "Build CMake project using Ccache"
description: "Build a CMake project. Save Ccache cache after a successful build."
inputs:
  vm:
    description: "The virtual machine used for the build."
    required: true
  build-dir:
    description: "The project's build directory"
    required: false
    default: "build"

runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ github.job }}-ccache-${{ github.run_id }}
        restore-keys: ${{ github.job }}-ccache-

    - shell: bash -e {0}
      run: |
        rsync --archive --stats ${{ env.CCACHE_DIR }}/ ${{ inputs.vm }}:${{ env.CCACHE_DIR }}

    - shell: ${{ inputs.vm }} {0}
      run: |
        set -e
        cd ${{ github.workspace }}
        ccache --zero-stats
        cmake --build ${{ inputs.build-dir }} -- -j ${{ env.CI_NCPU }}
        ccache --show-stats --verbose >/dev/null 2>&1 && ccache --show-stats --verbose || { ccache --version; ccache --show-stats; }

    - shell: bash -e {0}
      run: |
        rsync --archive --stats ${{ inputs.vm }}:${{ env.CCACHE_DIR }}/ ${{ env.CCACHE_DIR }}

    - shell: ${{ inputs.vm }} {0}
      run: |
        rm -rf ${{ env.CCACHE_DIR }}

    - uses: actions/cache/save@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ github.job }}-ccache-${{ github.run_id }}

    - shell: bash -e {0}
      run: |
        rm -rf ${{ env.CCACHE_DIR }}
