name: "Build CMake project using Ccache"
description: "Build a CMake project. Save Ccache cache after a successful build."
inputs:
  vm:
    description: "The virtual machine used for the build."
    required: true
  build-dir:
    description: "The project's build directory."
    required: false
    default: "${{ github.workspace }}/build"

runs:
  using: "composite"
  steps:
    - shell: ${{ inputs.vm }} {0}
      run: cmake --build ${{ inputs.build-dir }} -- -j ${{ env.CI_NCPU }}
