name: "Build Bitcoin Core depends"
description: "Build Bitcoin Core depends. Save the built packages cache after a successful build."
inputs:
  vm:
    description: "The virtual machine used for the build."
    required: true
  host:
    description: "The HOST variable definition."
    required: false
    default: ""
  cache-dir:
    description: "The built packages cache directory."
    required: false
    default: "${{ github.workspace }}/depends/built"
  options:
    description: "Additional depends build options."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: ${{ inputs.cache-dir }}
        key: ${{ github.job }}-depends-${{ hashFiles('depends/**') }}

    - if: steps.restore-cache.outputs.cache-hit == 'true'
      shell: bash -e {0}
      run: rsync --archive --stats ${{ inputs.cache-dir }}/ ${{ inputs.vm }}:${{ inputs.cache-dir }}

    - shell: ${{ inputs.vm }} {0}
      run: gmake -C ${{ github.workspace }}/depends -j ${{ env.CI_NCPU }} ${{ inputs.host }} BASE_CACHE=${{ inputs.cache-dir }} ${{ inputs.options }} LOG=1

    - if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash -e {0}
      run: rsync --archive --stats ${{ inputs.vm }}:${{ inputs.cache-dir }}/ ${{ inputs.cache-dir }}

    - if: steps.restore-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.cache-dir }}
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
