name: macOS, arm64
on:
  pull_request:
    paths:
      - '.github/workflows/macos.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: 'macOS 26 ARM64'
    runs-on: macos-26

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v7
        with:
          repository: bitcoin/bitcoin

      - name: Install dependencies
        run: |
          brew update
          brew install git cmake pkgconf boost zeromq qt qrencode capnp

      - name: Generate CTest configuration
        run: |
          cat << 'EOF' > ctest_config.cmake
          set(CTEST_SITE "${{ github.repository }}")
          set(CTEST_BUILD_NAME "macOS 26 ARM64")
          set(CTEST_SOURCE_DIRECTORY "$ENV{GITHUB_WORKSPACE}")
          set(CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build")
          set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
          EOF

      - name: CDash -- Start & Update
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(${{ case(github.event_name == 'workflow_run', 'Nightly', format('Experimental GROUP {0}', github.event_name)) }})
          find_program(CTEST_GIT_COMMAND git REQUIRED)
          set(CTEST_UPDATE_VERSION_ONLY TRUE)
          ctest_update()

      - name: CDash -- Configure
        shell: ctest --extra-verbose --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          set(configure_opts
            "--preset dev-mode"
            "-DWITH_USDT=OFF"
            "-DCMAKE_COMPILE_WARNING_AS_ERROR=ON"
          )
          ctest_start(APPEND)
          ctest_configure(OPTIONS "${configure_opts}")

      - name: CDash -- Build
        shell: ctest --extra-verbose --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_build(PARALLEL_LEVEL 4)

      - name: Check 'bitcoind' executable
        run: |
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          otool -L build/bin/bitcoind
          build/bin/bitcoind -version

      - name: CDash -- Test
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_test(PARALLEL_LEVEL 4)

      - name: CDash -- Submit
        if: always()
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_submit()

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          build/test/functional/test_runner.py -j 8 --combinedlogslen=99999999 \
            --extended
