name: NetBSD
on:
  pull_request:
    paths:
      - '.github/actions/build-depends/action.yml'
      - '.github/workflows/netbsd.yml'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name with owner'
        required: true
        default: bitcoin/bitcoin
        type: string
      ref:
        description: 'Repository reference: refs/heads/<branch>, refs/tags/<tag>, refs/pull/<PR>/head or refs/<commit>'
        required: true
        default: refs/heads/master
        type: string
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  # See https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4

jobs:
  netbsd-syslibs:
    name: 'NetBSD ${{ matrix.release }}, system libs, no GUI'
    runs-on: ubuntu-latest
    env:
      PACKAGES: 'boost sqlite3 zeromq'
    defaults:
      run:
        shell: netbsd {0}
    strategy: &RELEASE_MATRIX
      fail-fast: false
      matrix:
        # Test all supported releases.
        # See https://www.netbsd.org/releases/.
        include:
          - release: '10.1'

    steps:
      - &START_VM
        name: Start NetBSD VM
        uses: vmactions/netbsd-vm@v1
        with:
          release: ${{ matrix.release }}
          mem: 12288
          prepare: |
            echo "CHECK_OSABI=no" >> /etc/pkg_install.conf
            pkg_info > packages_before
            pkg_add -u cmake curl gcc14 lsof ninja-build pkgconf py313-zmq python313 ${{ env.PACKAGES }}
            pkg_info > packages_after
            diff -w packages_before packages_after | grep '^>'
          sync: no
          disable-cache: true

      # The preinstalled `devel/capnproto` package is broken.
      # See https://github.com/bitcoin-core/libmultiprocess/pull/196.
      - name: Build Cap'n Proto
        run: |
          set -e
          pkg_admin -K /usr/pkg/pkgdb fetch-pkg-vulnerabilities
          pkg_add -u digest libtool-base mktools cwrappers
          # https://www.netbsd.org/docs/pkgsrc/getting.html#getting-via-tar
          ftp ftp://ftp.NetBSD.org/pub/pkgsrc/stable/pkgsrc.tar.gz
          tar -xzf pkgsrc.tar.gz -C /usr \
            pkgsrc/devel/capnproto \
            pkgsrc/devel/libtool-base \
            pkgsrc/devel/pkgconf \
            pkgsrc/devel/zlib \
            pkgsrc/lang/gcc15 \
            pkgsrc/mk \
            pkgsrc/pkgtools \
            pkgsrc/security/openssl \
            pkgsrc/sysutils/install-sh/files
          cd /usr/pkgsrc/devel/capnproto
          unset PKG_PATH
          make CPPFLAGS="-DKJ_NO_EXCEPTIONS=0" install

      - &FETCH_SOURCE
        name: Fetch source tarball
        run: |
          set -e
          curl --location --fail --output source.tar.gz https://github.com/${{ inputs.repository || 'bitcoin/bitcoin' }}/archive/${{ inputs.ref || 'refs/heads/master' }}.tar.gz
          mkdir bitcoin
          tar -xf source.tar.gz -C bitcoin --strip-components=1
          rm -rf source.tar.gz
          # Test data.
          DIR_UNIT_TEST_DATA="$(pwd)/qa-assets/unit_test_data"
          mkdir -p "$DIR_UNIT_TEST_DATA"
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json

      - name: Generate CTest configuration
        run: |
          cat << 'EOF' > ctest_config.cmake
          set(CTEST_SITE "${{ github.repository }}")
          set(CTEST_BUILD_NAME "NetBSD ${{ matrix.release }}, system libs, no GUI")
          set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/bitcoin")
          set(CTEST_BINARY_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/build")
          set(CTEST_CMAKE_GENERATOR "Ninja")
          cmake_host_system_information(RESULT nproc QUERY NUMBER_OF_LOGICAL_CORES)
          EOF

      - &CDASH_START_UPDATE
        name: CDash -- Start & Update
        run: |
          COMMIT="$(awk -F '"' '/^#define GIT_COMMIT_ID/ {print $2}' bitcoin/src/clientversion.cpp)"
          echo "set(CTEST_UPDATE_VERSION_OVERRIDE $COMMIT)" >> ctest_update_version_override.cmake
          cat << 'EOF' > ctest_start_upate.cmake
          include(ctest_config.cmake)
          ctest_start(${{ case(github.event_name == 'workflow_run', 'Nightly', format('Experimental GROUP {0}', github.event_name)) }})
          set(CTEST_UPDATE_TYPE git)
          # This command may be redundant once the following MR is merged:
          # https://gitlab.kitware.com/cmake/cmake/-/merge_requests/12038
          set(CTEST_UPDATE_COMMAND "${CMAKE_COMMAND} -E true")
          include(ctest_update_version_override.cmake)
          ctest_update()
          EOF
          ctest --script ctest_start_upate.cmake
          # A hack to work around the broken CTEST_UPDATE_VERSION_OVERRIDE.
          sed -i 's/\([[:blank:]]*\)<UpdateType>Unknown<\/UpdateType>/\1<UpdateType>GIT<\/UpdateType>\
            \1<Revision>'"$COMMIT"'<\/Revision>/' "build/Testing/$(head -1 build/Testing/TAG)/Update.xml"

      - name: CDash -- Configure
        run: |
          cat << 'EOF' > ctest_configure.cmake
          include(ctest_config.cmake)
          set(configure_opts
            "--preset dev-mode"
            "-DCMAKE_C_COMPILER=/usr/pkg/gcc14/bin/gcc"
            "-DCMAKE_CXX_COMPILER=/usr/pkg/gcc14/bin/g++"
            "-DBUILD_GUI=OFF"
            "-DWITH_USDT=OFF"
            "-DCMAKE_COMPILE_WARNING_AS_ERROR=ON"
          )
          ctest_start(APPEND)
          ctest_configure(OPTIONS "${configure_opts}")
          EOF
          ctest --extra-verbose --script ctest_configure.cmake

      - &CDASH_BUILD
        name: CDash -- Build
        run: |
          cat << 'EOF' > ctest_build.cmake
          include(ctest_config.cmake)
          ctest_start(APPEND)
          ctest_build(PARALLEL_LEVEL ${nproc})
          EOF
          ctest --extra-verbose --script ctest_build.cmake

      - &CHECK_BITCOIND
        name: Check 'bitcoind' executable
        run: |
          set -e
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - &CDASH_TEST
        name: CDash -- Test
        run: |
          cat << 'EOF' > ctest_test.cmake
          include(ctest_config.cmake)
          set(ENV{DIR_UNIT_TEST_DATA} ${CTEST_SCRIPT_DIRECTORY}/qa-assets/unit_test_data)
          set(ENV{TMPDIR} ${CTEST_SCRIPT_DIRECTORY})
          ctest_start(APPEND)
          ctest_test(PARALLEL_LEVEL ${nproc})
          EOF
          ctest --script ctest_test.cmake

      - &CDASH_SUBMIT
        name: CDash -- Submit
        if: always()
        run: |
          cat << 'EOF' > ctest_submit.cmake
          include(ctest_config.cmake)
          ctest_start(APPEND)
          ctest_submit()
          EOF
          ctest --script ctest_submit.cmake

      - &CHECK_HOST_DISK_SPACE
        name: Check host disk space
        if: ${{ ! inputs.skip_functional_tests }}
        shell: bash
        run: df -h

      - &RUN_FUNCTIONAL_TESTS
        name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          set -e
          python3.13 build/test/functional/test_runner.py -j $((${{ env.CI_NCPU }} * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix . \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/33128.` \
            --exclude feature_reindex_init \
            `# p2p_invalid_messages causes OOM. Running separately in the next command.` \
            --exclude p2p_invalid_messages \
            `# TODO https://github.com/bitcoin/bitcoin/pull/35216` \
            --exclude feature_bind_extra \
            --exclude rpc_bind \
            --timeout-factor=8
          python3.13 build/test/functional/test_runner.py p2p_invalid_messages --combinedlogslen=99999999 \
            --tmpdirprefix . \
            --timeout-factor=8

  netbsd-depends:
    name: 'NetBSD ${{ matrix.release }}, depends'
    runs-on: ubuntu-latest
    env:
      PACKAGES: 'gmake perl'
    defaults:
      run:
        shell: netbsd {0}
    strategy: *RELEASE_MATRIX

    steps:
      - *START_VM
      - *FETCH_SOURCE

      - name: Checkout helper actions
        uses: actions/checkout@v7
        with:
          sparse-checkout: .github/actions/build-depends
          path: ci/nightly

      - name: Build depends
        uses: ./ci/nightly/.github/actions/build-depends
        with:
          vm: netbsd
          options: >
            build_CC=/usr/pkg/gcc14/bin/gcc
            build_CXX=/usr/pkg/gcc14/bin/g++
            CC=/usr/pkg/gcc14/bin/gcc
            CXX=/usr/pkg/gcc14/bin/g++
          source-dir: /root/bitcoin
          cache-tag: netbsd-${{ matrix.release }}

      - name: Generate CTest configuration
        run: |
          cat << 'EOF' > ctest_config.cmake
          set(CTEST_SITE "${{ github.repository }}")
          set(CTEST_BUILD_NAME "NetBSD ${{ matrix.release }}, depends")
          set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/bitcoin")
          set(CTEST_BINARY_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/build")
          set(CTEST_CMAKE_GENERATOR "Ninja")
          cmake_host_system_information(RESULT nproc QUERY NUMBER_OF_LOGICAL_CORES)
          EOF

      - *CDASH_START_UPDATE

      - name: CDash -- Configure
        run: |
          cat << 'EOF' > ctest_configure.cmake
          include(ctest_config.cmake)
          set(configure_opts
            "--toolchain /root/bitcoin/depends/x86_64-unknown-netbsd${{ matrix.release }}/toolchain.cmake"
            "--preset dev-mode"
            "-DBUILD_GUI=OFF"
            "-DWITH_USDT=OFF"
            "-DCMAKE_COMPILE_WARNING_AS_ERROR=ON"
          )
          ctest_start(APPEND)
          ctest_configure(OPTIONS "${configure_opts}")
          EOF
          ctest --extra-verbose --script ctest_configure.cmake

      - *CDASH_BUILD
      - *CHECK_BITCOIND
      - *CDASH_TEST
      - *CDASH_SUBMIT
      - *CHECK_HOST_DISK_SPACE
      - *RUN_FUNCTIONAL_TESTS
