name: Nightly Tests
on:
  push:

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXFILES: 2500
  DEPENDS_CACHE_DIR: ${{ github.workspace }}/depends/built
  # See https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
  CI_NCPU: 4

jobs:
  omnios:
    name: 'OmniOS: system libs, no GUI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: omnios {0}

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v4
        with:
          repository: hebasto/bitcoin
          ref: 241228-findbdb

      - name: Ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-ccache-${{ github.run_id }}
          restore-keys: ${{ github.job }}-ccache-

      - name: Start OmniOS VM
        uses: vmactions/omnios-vm@v1
        with:
          envs: 'CCACHE_DIR CCACHE_MAXFILES'
          prepare: |
            pkg list -H -o name,publisher,version > packages_before
            pkg install cmake gcc14 pkg-config ccache sqlite-3 bdb python-312
            pkg set-publisher -g https://sfe.opencsw.org/localhostomnios localhostomnios
            pkg install boost/header-boost libevent2
            pkg list -H -o name,publisher,version > packages_after
            diff -w packages_before packages_after | grep '^>'
          sync: 'rsync'
          copyback: false

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          cmake -B build -DCMAKE_LIBRARY_ARCHITECTURE="amd64" -DCMAKE_PREFIX_PATH="/opt/ooce;/usr/g++;/usr/gnu" -DWITH_BDB=ON -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=ON

      - name: Build
        run: |
          set -e
          cd ${{ github.workspace }}
          ccache --zero-stats
          cmake --build build -j ${{ env.CI_NCPU }}
          ccache --show-stats --verbose

      - name: Run test suite
        run: |
          cd ${{ github.workspace }}
          ctest --test-dir build -j ${{ env.CI_NCPU }} --output-on-failure

      - name: Sync caches back from VM
        shell: bash -e {0}
        run: |
          rsync --archive --stats omnios:${{ env.CCACHE_DIR }}/ ${{ env.CCACHE_DIR }}
