name: Nightly Tests
on:
  pull_request:
  schedule:
    - cron: '22 02 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  netbsd:
    name: 'NetBSD: system libs, no USDT, no GUI'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v4
        with:
          repository: bitcoin/bitcoin

      - name: Ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-ccache-${{ github.run_id }}
          restore-keys: ${{ github.job }}-ccache-

      - name: Build and test in NetBSD VM
        uses: vmactions/netbsd-vm@v1
        with:
          envs: 'CCACHE_DIR'
          prepare: |
            /usr/sbin/pkg_add cmake clang libcxx pkg-config ccache boost-headers libevent sqlite3 db4 zeromq
          run: |
            set -e
            cmake -B build -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++;-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-L/usr/pkg/lib" -DWITH_BDB=ON -DWITH_ZMQ=ON -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=ON
            ccache --zero-stats
            cmake --build build -j $(sysctl -n hw.ncpu)
            ccache --show-stats --verbose
            ctest --test-dir build -j $(sysctl -n hw.ncpu) --output-on-failure
            rm -rf build
