name: Nightly Tests
on:
  workflow_dispatch:

jobs:
  omnios:
    name: 'OmniOS: check predefined macros'
    runs-on: ubuntu-latest

    steps:
      - name: Start OmniOS VM
        uses: vmactions/omnios-vm@v1
        with:
          prepare: |
            pkg install gcc14

      - shell: omnios {0}
        run: /opt/gcc-14/bin/cpp -dM < /dev/null
