name: OpenIndiana
on:
  pull_request:
    paths:
      - '.github/workflows/openindiana.yml'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name with owner'
        required: true
        default: bitcoin/bitcoin
        type: string
      ref:
        description: 'Repository reference: refs/heads/<branch>, refs/tags/<tag>, refs/pull/<PR>/head or refs/<commit>'
        required: true
        default: refs/heads/master
        type: string
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  # See https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4

jobs:
  openindiana:
    name: 'OpenIndiana, SQLite ${{ matrix.sqlite_ver }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: openindiana {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - sqlite_ver: '3.51.0'
            sqlite_tar_ver: '3510000'
            sqlite_url: 'https://sqlite.org/2025'
          - sqlite_ver: '3.51.1'
            sqlite_tar_ver: '3510100'
            sqlite_url: 'https://sqlite.org/2025'
          - sqlite_ver: '3.51.2'
            sqlite_tar_ver: '3510200'
            sqlite_url: 'https://sqlite.org/2026'
          - sqlite_ver: '3.51.3'
            sqlite_tar_ver: '3510300'
            sqlite_url: 'https://sqlite.org/2026'
          - sqlite_ver: '3.52.0'
            sqlite_tar_ver: '3520000'
            sqlite_url: 'https://sqlite.org/2026'

    steps:
      - name: Start OpenIndiana VM
        # openindiana-vm@v1.0.9 introduces multiple regressions, including:
        # 1. A libc thread failure in the `coins_tests_base` test.
        # 2. Doubled build times.
        uses: vmactions/openindiana-vm@v1.0.8
        with:
          # This release has `metapackages/build-essential` preinstalled.
          release: '202510-build'
          mem: 18432
          sync: no
          disable-cache: true

      - name: Build Boost
        env:
          BOOST_VERSION: '1.91.0-1'
        run: |
          set -e
          curl --location --fail --output boost.tar.xz https://github.com/boostorg/boost/releases/download/boost-${{ env.BOOST_VERSION }}/boost-${{ env.BOOST_VERSION }}-cmake.tar.xz
          tar xf boost.tar.xz
          cmake -S boost-${{ env.BOOST_VERSION }} -B build-boost \
            -DBOOST_INCLUDE_LIBRARIES="multi_index;test" \
            -DBOOST_TEST_HEADERS_ONLY=ON \
            -DBOOST_ENABLE_MPI=OFF \
            -DBOOST_ENABLE_PYTHON=OFF \
            -DBOOST_INSTALL_LAYOUT=system \
            -DBUILD_TESTING=OFF \
            -DCMAKE_DISABLE_FIND_PACKAGE_ICU=ON
          cmake --install build-boost

      # The preinstalled `database/sqlite-3` package is broken.
      # For details, see https://github.com/bitcoin/bitcoin/issues/34163.
      - name: Build SQLite
        run: |
          set -e
          curl --location --fail --output sqlite.tar.gz ${{ matrix.sqlite_url }}/sqlite-autoconf-${{ matrix.sqlite_tar_ver }}.tar.gz
          tar xf sqlite.tar.gz
          cd sqlite-autoconf-${{ matrix.sqlite_tar_ver }}
          ./configure
          gmake -j ${{ env.CI_NCPU }}
          gmake INSTALL=ginstall install

      - name: Fetch source tarball
        run: |
          set -e
          curl --location --fail --output source.tar.gz https://github.com/${{ inputs.repository || 'bitcoin/bitcoin' }}/archive/${{ inputs.ref || 'refs/heads/master' }}.tar.gz
          mkdir bitcoin
          gtar -xf source.tar.gz -C bitcoin --strip-components=1
          rm -rf source.tar.gz

      - name: Generate buildsystem
        run: |
          # Workaround for a bug in the FindThreads module.
          # See https://gitlab.kitware.com/cmake/cmake/-/issues/26063.
          export CXXFLAGS="-pthread"
          cmake -S bitcoin -B build \
            -Wno-error=dev \
            -DCMAKE_PREFIX_PATH=/usr/local \
            `# TODO: Build Cap'n Proto from source and reenable IPC.` \
            -DENABLE_IPC=OFF \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - name: Build
        run: |
          cmake --build build -- -j ${{ env.CI_NCPU }}

      - name: Check 'bitcoind' executable
        run: |
          set -e
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - name: Run test suite
        run: |
          set -e
          export DIR_UNIT_TEST_DATA="$(pwd)/qa-assets/unit_test_data"
          mkdir -p ${DIR_UNIT_TEST_DATA}
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json
          ctest --test-dir build -j ${{ env.CI_NCPU }} --output-on-failure

      - name: Check host disk space
        if: ${{ ! inputs.skip_functional_tests }}
        shell: bash
        run: df -h

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          # Not running extended tests to avoid disk space issues.
          python3.14 build/test/functional/test_runner.py -j ${{ env.CI_NCPU }} --combinedlogslen=99999999 \
            --tmpdirprefix . \
            `# See https://github.com/bitcoin/bitcoin/issues/33128.` \
            --exclude feature_reindex_init \
            `# TODO: Investigate the failure.` \
            --exclude interface_bitcoin_cli \
            `# TODO https://github.com/bitcoin/bitcoin/pull/35216` \
            --exclude feature_bind_extra \
            --exclude rpc_bind \
            --timeout-factor=8
