name: OpenIndiana
on:
  pull_request:
    paths:
      - '.github/workflows/openindiana.yml'

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  openindiana_v108:
    name: 'OpenIndiana v1.0.8'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: openindiana {0}

    steps:
      - &FETCH_SOURCE
        name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: bitcoin/bitcoin

      - name: Start OpenIndiana VM
        uses: vmactions/openindiana-vm@v1.0.8
        with:
          release: '202510-build'
          prepare: pkg install developer/build/pkgconf
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - &BUILD_BOOST
        name: Build Boost
        run: |
          set -e
          curl --location --fail --output boost-1.90.0-cmake.tar.xz https://github.com/boostorg/boost/releases/download/boost-1.90.0/boost-1.90.0-cmake.tar.xz
          tar xf boost-1.90.0-cmake.tar.xz
          cmake -S boost-1.90.0 -B build-boost \
            -DBOOST_INCLUDE_LIBRARIES="multi_index;signals2;test" \
            -DBOOST_TEST_HEADERS_ONLY=ON \
            -DBOOST_ENABLE_MPI=OFF \
            -DBOOST_ENABLE_PYTHON=OFF \
            -DBOOST_INSTALL_LAYOUT=system \
            -DBUILD_TESTING=OFF \
            -DCMAKE_DISABLE_FIND_PACKAGE_ICU=ON
          cmake --install build-boost

      - &CONFIGURE
        name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          export CXXFLAGS="-pthread"
          cmake -B build \
            -Wno-error=dev \
            -DCMAKE_PREFIX_PATH=/usr/local \
            -DENABLE_WALLET=OFF \
            -DENABLE_IPC=OFF \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - &BUILD
        name: Build
        run: |
          cd ${{ github.workspace }}
          cmake --build build -- -j 4

      - &RUN_TESTS
        name: Run test suite
        run: |
          cd ${{ github.workspace }}
          ctest --test-dir build -j 4 --output-on-failure

  openindiana_v109:
    name: 'OpenIndiana v1.0.9'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: openindiana {0}

    steps:
      - *FETCH_SOURCE

      - name: Start OpenIndiana VM
        uses: vmactions/openindiana-vm@v1.0.9
        with:
          release: '202510-build'
          prepare: pkg install developer/build/pkgconf
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - *BUILD_BOOST
      - *CONFIGURE
      - *BUILD
      - *RUN_TESTS
