name: Windows, clang-cl, arm64
on:
  pull_request:
    paths:
      - '.github/workflows/windows-clang-cl-arm64.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  windows-native:
    name: 'Windows ARM64, clang-cl'
    runs-on: windows-11-arm
    defaults:
      run:
        shell: pwsh -Command "$PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'Stop'; & '{0}'"

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: bitcoin/bitcoin
          ref: refs/pull/31507/merge

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        # Using microsoft/setup-msbuild is not enough.
        uses: ilammy/msvc-dev-cmd@v1

      - name: Get tool information
        run: |
          cmake -version
          Write-Host "---"
          clang-cl --version
          Write-Host "---"
          Write-Host "VCToolsVersion: $env:VCToolsVersion"
          Write-Host "---"
          py -3 --version
          Write-Host "---"
          Write-Host "PowerShell version $($PSVersionTable.PSVersion.ToString())"

      - name: Set vcpkg build type
        run: |
          Add-Content -Path "$env:VCPKG_ROOT\triplets\arm64-windows.cmake" -Value "set(VCPKG_BUILD_TYPE release)"

      - name: Generate buildsystem
        env:
          CXXFLAGS: '-Wno-return-type -Wno-error=unused-private-field -Wno-error=conditional-uninitialized'
        run: |
          cmake -B build --preset windows -DVCPKG_TARGET_TRIPLET=arm64-windows -DBUILD_UTIL_CHAINSTATE=ON -DBUILD_BENCH=ON -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - name: Build
        working-directory: build
        run: |
          cmake --build . -j $env:NUMBER_OF_PROCESSORS --config Release

      - name: Run test suite
        working-directory: build
        run: |
          ctest -j $env:NUMBER_OF_PROCESSORS --output-on-failure -C Release

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        working-directory: build
        env:
          PYTHONUTF8: 1
          BITCOIN_BIN: '${{ github.workspace }}\build\bin\Release\bitcoin.exe'
          BITCOIND: '${{ github.workspace }}\build\bin\Release\bitcoind.exe'
          BITCOINCLI: '${{ github.workspace }}\build\bin\Release\bitcoin-cli.exe'
          BITCOIN_BENCH: '${{ github.workspace }}\build\bin\Release\bench_bitcoin.exe'
          BITCOINTX: '${{ github.workspace }}\build\bin\Release\bitcoin-tx.exe'
          BITCOINUTIL: '${{ github.workspace }}\build\bin\Release\bitcoin-util.exe'
          BITCOINWALLET: '${{ github.workspace }}\build\bin\Release\bitcoin-wallet.exe'
          BITCOINCHAINSTATE: '${{ github.workspace }}\build\bin\Release\bitcoin-chainstate.exe'
          TEST_RUNNER_EXTRA: ${{ github.event_name != 'pull_request' && '--extended' || '' }}
        shell: bash
        run: |
          py -3 -m pip install pyzmq
          py -3 test/functional/test_runner.py -j $(($NUMBER_OF_PROCESSORS * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix "$RUNNER_TEMP" \
            --extended \
            --timeout-factor=40
