name: Windows, UCRT
on:
  pull_request:
    paths:
      - '.github/actions/**'
      - '.github/workflows/windows-ucrt.yml'
  schedule:
    - cron: '22 02 * * *'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CI_HOST: x86_64-w64-mingw32ucrt

jobs:
  windows-cross:
    name: 'Windows, cross-build only, UCRT: no GUI'
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v4
        with:
          repository: hebasto/bitcoin
          ref: 241203-multiwallet

      - name: Install dependencies
        run: |
          dnf install -y cmake make patch ucrt64-gcc-c++ which

      - name: Build depends
        run: |
          gmake -C depends -j $(nproc) HOST=${{ env.CI_HOST }} mingw32_CC=/usr/bin/${{ env.CI_HOST }}-gcc mingw32_CXX=/usr/bin/${{ env.CI_HOST }}-g++ NO_QT=1 LOG=1

      - name: Generate buildsystem
        run: >
          cmake -B build \
            --toolchain depends/${{ env.CI_HOST }}/toolchain.cmake \
            -DREDUCE_EXPORTS=ON \
            -DBUILD_BENCH=ON \
            -DBUILD_FUZZ_BINARY=ON \
            -DWERROR=ON \
            -DAPPEND_CXXFLAGS='-Wno-error=maybe-uninitialized -Wno-error=array-bounds'

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Upload built executables
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}
          path: |
            build/src/**/*.exe
            build/test/config.ini

  windows-native-test:
    name: 'Windows, test cross-built executables natively'
    runs-on: windows-latest
    needs: windows-cross

    env:
      PYTHONUTF8: 1
      TEST_RUNNER_TIMEOUT_FACTOR: 40

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v4
        with:
          repository: hebasto/bitcoin
          ref: 241203-multiwallet

      - name: Download built executables
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}

      - name: Run bitcoind.exe
        run: .\src\bitcoind.exe -version

      - name: Run unit tests
        run: |
          .\src\test\test_bitcoin.exe -l test_suite
          .\src\secp256k1\bin\exhaustive_tests.exe
          .\src\secp256k1\bin\noverify_tests.exe
          .\src\secp256k1\bin\tests.exe
          .\src\univalue\object.exe
          .\src\univalue\unitester.exe

      - name: Run benchmarks
        run: .\src\bench\bench_bitcoin.exe -sanity-check -priority-level=high

      - name: Adjust paths in test\config.ini
        run: |
          (Get-Content "test\config.ini") -replace '(?<=^SRCDIR=).*', '${{ github.workspace }}' -replace '(?<=^BUILDDIR=).*', '${{ github.workspace }}' -replace '(?<=^RPCAUTH=).*', '${{ github.workspace }}\share\rpcauth\rpcauth.py' | Set-Content "test\config.ini"
          Get-Content "test\config.ini"

      - name: Run util tests
        run: py -3 test\util\test_runner.py

      - name: Run rpcauth test
        run: py -3 test\util\rpcauth-test.py

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        shell: cmd
        run: py -3 test\functional\test_runner.py --jobs %NUMBER_OF_PROCESSORS% --ci --quiet --tmpdirprefix=%RUNNER_TEMP% --combinedlogslen=99999999 --timeout-factor=%TEST_RUNNER_TIMEOUT_FACTOR% --extended
