name: "Run Bitcoin Core test suite"
description: "Execute the Bitcoin Core test suite using the fetched unit_test_data/script_assets_test.json file."
inputs:
  vm:
    description: "The virtual machine to run the test suite."
    required: true
  build-dir:
    description: "The project's build directory."
    required: false
    default: "${{ github.workspace }}/build"
  envs:
    description: "Environment variables for the ctest command."
    required: false
    default: ""
  options:
    description: "Additional options for the ctest command."
    required: false
    default: ""
  unit-test-data-dir:
    description: "The location of the script_assets_test.json file."
    required: false
    default: "${{ github.workspace }}/qa-assets/unit_test_data"

runs:
  using: "composite"
  steps:
    - shell: bash -e {0}
      run: |
        mkdir -p ${{ inputs.unit-test-data-dir }}
        ./ci/retry/retry -- curl --location --fail https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json --output ${{ inputs.unit-test-data-dir }}/script_assets_test.json
        rsync --archive --mkpath ${{ inputs.unit-test-data-dir }}/ ${{ inputs.vm }}:${{ inputs.unit-test-data-dir }}

    - shell: ${{ inputs.vm }} {0}
      run: |
        cmake -E env DIR_UNIT_TEST_DATA=${{ inputs.unit-test-data-dir }} ${{ inputs.envs }} ctest --test-dir ${{ inputs.build-dir }} -j ${{ env.CI_NCPU }} --output-on-failure ${{ inputs.options }}
